### ISSUE TITLE
Re-indexing work/needs

### ISSUE THREAD

**Issue by hifilorau** [clinwiki-org/clinwiki#1013]
Right now, the biggest issue besides we only have a hack is that our hack doesn't also index the wiki_edits or crowd_edits if i'm not mistaken. I think we need to make sure our full index function indexes everything.

**Comment by hifilorau** [comment]
Do these get put back into the queue on this error.

```
error: duplicate key value violates unique constraint "locations_pkey"
    at Parser.parseErrorMessage (/nodejs/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/nodejs/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/nodejs/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/nodejs/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 197,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (id)=(257881) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'locations',
  column: undefined,
  dataType: undefined,
  constraint: 'locations_pkey',
  file: 'nbtinsert.c',
  line: '534',
  routine: '_bt_check_unique'
}
```
